# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bank-queue-db
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bank_queue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
